run: FlightManagementSystem.class
	java com/main/FlightManagementSystem

FlightManagementSystem.class: com/main/FlightManagementSystem.java
	javac com/main/FlightManagementSystem.java

clean:
	rm com/*/*.class